/*
 * generated by Xtext
 */
package edu.unq.objetos3.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PlanificacionConferenciaUiModule extends edu.unq.objetos3.ui.AbstractPlanificacionConferenciaUiModule {
	public PlanificacionConferenciaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
