/*
 * generated by Xtext
 */
package edu.unq.objetos3.validation

import org.eclipse.xtext.validation.Check
import edu.unq.objetos3.planificacionConferencia.Charla
import edu.unq.objetos3.planificacionConferencia.PlanificacionConferenciaPackage

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class PlanificacionConferenciaValidator extends AbstractPlanificacionConferenciaValidator {

	@Check
	def checkDuracionMinimaCharla(Charla charla) {
		if (charla.duracion < 30) {
			error('Una charla no puede durar menos de 30 minutos', 
					PlanificacionConferenciaPackage.Literals.CHARLA__DURACION, 
					'duracionMinimaCharla')
		}
	}
}
