/*
 * generated by Xtext
 */
package edu.unq.objetos3.ui.contentassist

import edu.unq.objetos3.ui.contentassist.AbstractPlanificacionConferenciaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PlanificacionConferenciaProposalProvider extends AbstractPlanificacionConferenciaProposalProvider {
}
