/*
* generated by Xtext
*/
package edu.unq.objetos3;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PlanificacionConferenciaStandaloneSetup extends PlanificacionConferenciaStandaloneSetupGenerated{

	public static void doSetup() {
		new PlanificacionConferenciaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

