/*
 * generated by Xtext
 */
package edu.unq.objetos3;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlanificacionConferenciaRuntimeModule extends edu.unq.objetos3.AbstractPlanificacionConferenciaRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return PlanificacionConferenciaConverterService.class;
	}	
}
